# Generated by Django 2.2.5 on 2019-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_identify', '0002_auto_20190923_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvoice',
            name='description',
            field=models.CharField(default='NA', max_length=600),
        ),
    ]
