# Generated by Django 2.2.5 on 2019-09-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_identify', '0003_uploadvoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
