# Generated by Django 2.2.5 on 2019-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_identify', '0004_auto_20190923_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvoice',
            name='emotion',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
