# Generated by Django 2.2.5 on 2019-10-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_identify', '0006_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='NA', max_length=600)),
                ('emotion', models.CharField(default='NA', max_length=100)),
                ('audio', models.FileField(upload_to='sample/')),
            ],
        ),
        migrations.DeleteModel(
            name='Samples',
        ),
    ]
